export const DEFAULT_CITY = 'durham';
export const DEFAULT_CITY_CENTER = { lat: 35.9940, lng: -78.8986 }; // Downtown Durham

// Simple ~10km city bounding box for filtering (rough dev bounds)
export const CITY_BOUNDS = {
  minLat: 35.93,
  maxLat: 36.06,
  minLng: -78.98,
  maxLng: -78.83,
};

// Durham recommended locations (seed data for dev)
export const DURHAM_RECS = [
  // Duke Campus Locations (25)
  {
    id: 'duke-chapel',
    name: 'Duke University Chapel',
    lat: 36.0019,
    lng: -78.9395,
    category: 'Sight',
  },
  {
    id: 'duke-gardens',
    name: 'Sarah P. Duke Gardens',
    lat: 36.0003,
    lng: -78.9369,
    category: 'Garden',
    landmarks: ['Garden fountain', 'Terrace gardens entrance', 'Visitor center'],
  },
  {
    id: 'nasher-museum',
    name: 'Nasher Museum of Art',
    lat: 36.0023,
    lng: -78.9381,
    category: 'Museum',
  },
  {
    id: 'perkins-library',
    name: 'Perkins Library',
    lat: 35.9979,
    lng: -78.9377,
    category: 'Library',
  },
  {
    id: 'brodhead-center',
    name: 'Brodhead Center',
    lat: 36.0009,
    lng: -78.9391,
    category: 'Student Center',
  },
  {
    id: 'wilson-gym',
    name: 'Wilson Recreation Center',
    lat: 35.9987,
    lng: -78.9408,
    category: 'Gym',
  },
  {
    id: 'cameron-stadium',
    name: 'Cameron Indoor Stadium',
    lat: 36.0014,
    lng: -78.9403,
    category: 'Stadium',
  },
  {
    id: 'duke-forest',
    name: 'Duke Forest',
    lat: 35.9856,
    lng: -78.9434,
    category: 'Park',
  },
  {
    id: 'duke-east-campus',
    name: 'Duke East Campus',
    lat: 36.0033,
    lng: -78.9135,
    category: 'Campus',
  },
  {
    id: 'lilly-library',
    name: 'Lilly Library',
    lat: 36.0030,
    lng: -78.9142,
    category: 'Library',
  },
  {
    id: 'duke-gardens-cafe',
    name: 'Duke Gardens Terrace Cafe',
    lat: 36.0022,
    lng: -78.9379,
    category: 'Café',
  },
  {
    id: 'duke-west-union',
    name: 'West Union',
    lat: 36.0007,
    lng: -78.9388,
    category: 'Student Center',
  },
  {
    id: 'duke-divinity-school',
    name: 'Duke Divinity School',
    lat: 36.0031,
    lng: -78.9409,
    category: 'School',
  },
  {
    id: 'duke-law-school',
    name: 'Duke Law School',
    lat: 36.0041,
    lng: -78.9387,
    category: 'School',
  },
  {
    id: 'duke-medical-center',
    name: 'Duke University Hospital',
    lat: 36.0105,
    lng: -78.9370,
    category: 'Hospital',
  },
  {
    id: 'duke-bryan-center',
    name: 'Bryan University Center',
    lat: 36.0009,
    lng: -78.9383,
    category: 'Student Center',
  },
  {
    id: 'duke-quad',
    name: 'Main Quad',
    lat: 36.0012,
    lng: -78.9390,
    category: 'Park',
  },
  {
    id: 'fuqua-school',
    name: 'Fuqua School of Business',
    lat: 36.0078,
    lng: -78.9445,
    category: 'School',
  },
  {
    id: 'duke-box',
    name: 'The Box at Duke',
    lat: 36.0008,
    lng: -78.9385,
    category: 'Café',
  },
  {
    id: 'duke-marketplace',
    name: 'Duke Marketplace',
    lat: 36.0010,
    lng: -78.9392,
    category: 'Restaurant',
  },
  {
    id: 'duke-fitness-center',
    name: 'Brodie Gym',
    lat: 35.9992,
    lng: -78.9405,
    category: 'Gym',
  },
  {
    id: 'duke-cardio-tennis',
    name: 'Duke Tennis Center',
    lat: 36.0015,
    lng: -78.9420,
    category: 'Sports',
  },
  {
    id: 'duke-golf-course',
    name: 'Duke Golf Club',
    lat: 35.9890,
    lng: -78.9520,
    category: 'Sports',
  },
  {
    id: 'duke-marine-lab',
    name: 'Duke Marine Lab Building',
    lat: 36.0020,
    lng: -78.9365,
    category: 'Lab',
  },
  {
    id: 'duke-french-science',
    name: 'French Science Center',
    lat: 35.9995,
    lng: -78.9385,
    category: 'Lab',
  },

  // Downtown Durham Locations (25)
  {
    id: 'durham-central-park',
    name: 'Durham Central Park',
    lat: 36.0032,
    lng: -78.9037,
    category: 'Park',
    landmarks: ['Main entrance', 'Playground', 'Pavilion'],
  },
  {
    id: 'american-tobacco-campus',
    name: 'American Tobacco Campus',
    lat: 35.9931,
    lng: -78.9040,
    category: 'Mixed-use / Hangout',
    landmarks: ['Lucky Strike Tower', 'Central courtyard', 'Water feature'],
  },
  {
    id: 'dbap',
    name: 'Durham Bulls Athletic Park',
    lat: 35.9916,
    lng: -78.9058,
    category: 'Stadium',
  },
  {
    id: 'ninth-street',
    name: 'Ninth Street',
    lat: 36.0085,
    lng: -78.9255,
    category: 'Street / Cafés',
  },
  {
    id: 'fullsteam-brewery',
    name: 'Fullsteam Brewery',
    lat: 35.9945,
    lng: -78.8985,
    category: 'Brewery',
    landmarks: ['Bar area', 'Patio entrance', 'Front door'],
  },
  {
    id: 'motorco-music-hall',
    name: 'Motorco Music Hall',
    lat: 36.0025,
    lng: -78.9015,
    category: 'Music Venue',
  },
  {
    id: 'durham-food-hall',
    name: 'The Parlour Ice Cream',
    lat: 36.0089,
    lng: -78.9243,
    category: 'Dessert',
  },
  {
    id: 'cocoa-cinnamon',
    name: 'Cocoa Cinnamon',
    lat: 36.0087,
    lng: -78.9251,
    category: 'Café',
    landmarks: ['Espresso bar', 'Window seating', 'Front counter'],
  },
  {
    id: 'durham-farmers-market',
    name: "Durham Farmers' Market",
    lat: 36.0035,
    lng: -78.9041,
    category: 'Market',
  },
  {
    id: 'brightleaf-square',
    name: 'Brightleaf Square',
    lat: 35.9944,
    lng: -78.9023,
    category: 'Shopping',
  },
  {
    id: 'rue-cler',
    name: 'Rue Cler',
    lat: 36.0091,
    lng: -78.9249,
    category: 'French Café',
  },
  {
    id: 'ponysaurus-brewing',
    name: 'Ponysaurus Brewing',
    lat: 36.0026,
    lng: -78.9018,
    category: 'Brewery',
  },
  {
    id: 'dpac',
    name: 'Durham Performing Arts Center',
    lat: 35.9963,
    lng: -78.9020,
    category: 'Theater',
  },
  {
    id: '21c-museum',
    name: '21c Museum Hotel',
    lat: 35.9967,
    lng: -78.9013,
    category: 'Museum',
  },
  {
    id: 'the-cookery',
    name: 'The Cookery',
    lat: 35.9945,
    lng: -78.8988,
    category: 'Restaurant',
  },
  {
    id: 'guglhupf-bakery',
    name: 'Guglhupf Bakery',
    lat: 35.9943,
    lng: -78.8991,
    category: 'Bakery',
  },
  {
    id: 'bull-city-burger',
    name: 'Bull City Burger',
    lat: 35.9958,
    lng: -78.9019,
    category: 'Restaurant',
  },
  {
    id: 'parizade',
    name: 'Parizade',
    lat: 36.0092,
    lng: -78.9248,
    category: 'Restaurant',
  },
  {
    id: 'panzanella',
    name: 'Panzanella',
    lat: 35.9941,
    lng: -78.9271,
    category: 'Restaurant',
  },
  {
    id: 'ninth-street-bakery',
    name: 'Ninth Street Bakery',
    lat: 35.9937,
    lng: -78.9277,
    category: 'Bakery',
  },
  {
    id: 'wine-authorities',
    name: 'Wine Authorities',
    lat: 35.9942,
    lng: -78.9269,
    category: 'Bar',
  },
  {
    id: 'motorco-parts',
    name: 'Motorco Parts & Labor',
    lat: 36.0027,
    lng: -78.9013,
    category: 'Restaurant',
  },
  {
    id: 'durham-hotel',
    name: 'The Durham Hotel',
    lat: 35.9950,
    lng: -78.9030,
    category: 'Hotel',
  },
  {
    id: 'boxyard',
    name: 'Boxyard RTP',
    lat: 35.9952,
    lng: -78.9010,
    category: 'Shopping',
  },
  {
    id: 'copa',
    name: 'Copa',
    lat: 35.9948,
    lng: -78.9025,
    category: 'Restaurant',
  },
];
