// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptyagqwcbqxhfjzgijtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0eWFncXdjYnF4aGZqemdpanRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NDQ4ODAsImV4cCI6MjA3NzAyMDg4MH0.oWCUTteRB8J7PT_oR1QBReFOX74s4Uo2uO-V5AZE1qE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});